### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by tillea** [nvalimak/fsm-lite#3]
Hi,

I'd like to package fsm-lite for Debian on behalf of the Debian Med team.  To do so I have created the needed code for packaging but I'm lacking a license statement for fsm-lite.  I'd recommend something like GPL or BSD or some other widely used license.

I have further remarks:

1. It would be really nice if you would use release tags to inform others what commit you consider a stable version
2. Your code contains a fixed local path to sdsl library (/Users/nvalimak/code/sdsl-lite-2.0.3).  That's not a good idea for a public release.  The best idea would be to have a build system that detects the installation of the library.  (automake or cmake come to mind here).
3. For the packaging I've written a simple manpage.  You are welcome to include this.  Just tell me if you are interested.

Kind regards and thanks for considering a free license

         Andreas.

**Comment by nvalimak** [comment]
Created LICENSE.md and added the first release. John Lees already updated the Makefile, but I'll see about the build system options.
